# 🧑‍🚀 Tensorflow

TensorFlow é um framework de código aberto para computação numérica baseada em grafos computacionais, otimizado para aprendizado de máquina e deep learning, permitindo execução distribuída em CPUs, GPUs e TPUs.

Principais características

✅ Manipulação de tensores: O nome "TensorFlow" vem do fluxo (flow) de tensores através de operações matemáticas.

✅ Execução distribuída: Suporte a múltiplas CPUs, GPUs e TPUs para otimizar o desempenho.

✅ APIs de alto e baixo nível: Fornece desde o tf.keras (alto nível) até operações matemáticas de baixo nível.

✅ Compatibilidade com diversos dispositivos: Funciona em desktops, servidores, dispositivos móveis e até navegadores.

✅ Treinamento e inferência otimizados: Permite treinar modelos com grandes volumes de dados e otimizá-los para deployment.

Em **95%** dos casos de uso que você encontrará não exigirão nada além da tf.keras, mas vários mecanismos complexos que exigem processamento massivo de dados utilizam tensoflow, aplicações como o *sistema de recomendação do spotify*, *mecanismos de busca da google*, *recomendação de vídeos no youtube*, *recomendação e preços do airbnb* entre outras aplicações. Qualquer aplicação Keras está usando Tensorflow "indiretamente" pois keras é uma API de alto nível dentro do tensorflow: **tf.keras**.

# 🎲 Tensors e Operações

Geralmente, um *tensor* é um array multidimensional, exatamente com oum *ndarray* da **NumPy**, mas ele também pode conter um escalar (um valor simples, como 42). Esses tensores sãoimportantes para criar funções de custos e métricas customizadas, camadas personalizadas etc.

In [1]:
import tensorflow as tf

In [2]:
tf.constant([[1., 2., 3.], [4., 5., 6.]]) #Matriz

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [3]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

podemos ver o shape e o dtype dessas constants

In [4]:
array_tf = tf.constant([[1., 2., 3.], [4., 5., 6.]]) #Matriz
array_tf.shape

TensorShape([2, 3])

In [5]:
array_tf.dtype

tf.float32

indexação funciona como no numpy

In [6]:
array_tf[:, 1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [7]:
array_tf[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

tipo de operações

In [8]:
tf.square(array_tf)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [9]:
array_tf + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [10]:
array_tf @ tf.transpose(array_tf) # O @ é uma multiplicação de matrizes, note que ela multiplicou seus valores, nesse caso, está trocando as linhas pelas colunas com o transpose

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

essas não são as únicas operações possíveis, o TensorFlow basicamente faz tudo o que o numpy faz, algumas funções podem ter nomes diferentes, mas se procurar, achará.

# 📗 Tensores e numpy

É possível criar um tensor a partir de um array *NumPy* e vice-versa:

In [11]:
import numpy as np

In [12]:
a = np.array([2., 4., 5.])
a

array([2., 4., 5.])

In [13]:
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [14]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [15]:
np.square(array_tf)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

O TensorFlow não faz nenhuma conversão de tipos, caso tente realizar alguma opreção com tipos diferentes de variáveis, obterá um erro:

In [17]:
tf.constant(2.) + tf.constant(40)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 

o erro abaixo é pelo fato do tensorflow utilizar float32 ao invés de float64, essa diferença ajuda na performance.

In [18]:
tf.constant(2.) + tf.constant(40., dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2] name: 

se precisar converter um tipo, utilize o **tf.cast**

In [19]:
t2 = tf.constant(40., dtype=tf.float64)

In [20]:
tf.constant(2.0) + tf.cast(t2, tf.float32) # convertendo primeiro para float32

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

# 🎲 Variáveis

Os valores de tf.Tensor são imutáveis, não podemos utilizar tensors regulares para implementar pesos em uma rede neural, pois eles precisam ser ajustados pela retropropagação. Além disso, outros parâmtros também precisam mudar ao longo do tempo, para isso, utilizamos variáveis tensors:

Essa parte dificilmente é usada, pois para adicionarmos pesos temos o **add_weight()**, além de que parâmetros já são atualizados pelos otimizadores.

In [21]:
a = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
a

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [22]:
a.assign(2 * a)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [23]:
a[:, 2].assign([0., 1.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  0.],
       [ 8., 10.,  1.]], dtype=float32)>

In [24]:
a.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[100., 200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,   4.,   0.],
       [  8.,  10., 200.]], dtype=float32)>

# 📥 Gráfos

No TensorFlow, um grafo computacional (ou apenas "grafo") é uma representação dos cálculos como um conjunto de nós (operações) e arestas (dados que fluem entre essas operações).

Em vez de executar cada operação imediatamente (como no Python puro), o TensorFlow pode construir um grafo primeiro e depois executá-lo de forma otimizada. Isso é útil para acelerar cálculos, especialmente em GPUs e TPUs.

✅ **Definição**: O TensorFlow constrói um grafo computacional quando você define funções decoradas com @tf.function.

✅ **Otimização**: O grafo otimiza as operações, eliminando redundâncias e paralelizando cálculos.

✅ **Execução**: O grafo pode ser salvo, carregado e executado várias vezes sem precisar ser redefinido.

Abaixo tem um exemplo bem simples de uma função Tensor, ela processa uma entrada e, se for uma string, o último caractere é removido; se for um float, ele é convertido em inteiro:

In [36]:
import tensorflow as tf

@tf.function
def process_input(x):
    if tf.is_tensor(x):  # Garantindo que seja um tensor
        x = tf.convert_to_tensor(x)

    # Caso x seja uma string
    if x.dtype == tf.string:
        # Se o tensor for escalar (rank 0), usamos substr para remover o último caractere
        if x.shape.rank == 0:
            return tf.strings.substr(x, 0, tf.strings.length(x) - 1)  # Remove o último caractere
        else:
            return x[:, :-1]  # Caso contrário, pode-se realizar o slicing para tensores maiores
    # Caso x seja um float
    elif x.dtype == tf.float32 or x.dtype == tf.float64:
        return tf.cast(x, tf.int32)  # Converte para inteiro
    else:
        return x  # Retorna o original se não for string ou float

# Testando com diferentes entradas
input_float = tf.constant(3.7, dtype=tf.float32)
input_string = tf.constant("Hello", dtype=tf.string)

output_float = process_input(input_float)
output_string = process_input(input_string)

print(f"Entrada Float: {input_float.numpy()} → Saída: {output_float.numpy()}")
print(f"Entrada String: {input_string.numpy().decode()} → Saída: {output_string.numpy().decode()}")

Entrada Float: 3.700000047683716 → Saída: 3
Entrada String: Hello → Saída: Hell


Há uma infinidade de possibilidades com o uso de Tensors. O principal objetivo é a otimização no tratamento de dados em grande escala. A seguir, teremos um capítulo dedicado ao pipeline de processamento de dados volumosos. Continue com o [PreProcessingTensorFlow.ipynb](PreProcessingTensorFlow.ipynb)