# 🧑‍🚀 Tensorflow

TensorFlow é um framework de código aberto para computação numérica baseada em grafos computacionais, otimizado para aprendizado de máquina e deep learning, permitindo execução distribuída em CPUs, GPUs e TPUs.

Principais características

✅ Manipulação de tensores: O nome "TensorFlow" vem do fluxo (flow) de tensores através de operações matemáticas.

✅ Execução distribuída: Suporte a múltiplas CPUs, GPUs e TPUs para otimizar o desempenho.

✅ APIs de alto e baixo nível: Fornece desde o tf.keras (alto nível) até operações matemáticas de baixo nível.

✅ Compatibilidade com diversos dispositivos: Funciona em desktops, servidores, dispositivos móveis e até navegadores.

✅ Treinamento e inferência otimizados: Permite treinar modelos com grandes volumes de dados e otimizá-los para deployment.

Em **95%** dos casos de uso que você encontrará não exigirão nada além da tf.keras, mas vários mecanismos complexos que exigem processamento massivo de dados utilizam tensoflow, aplicações como o *sistema de recomendação do spotify*, *mecanismos de busca da google*, *recomendação de vídeos no youtube*, *recomendação e preços do airbnb* entre outras aplicações. Qualquer aplicação Keras está usando Tensorflow "indiretamente" pois keras é uma API de alto nível dentro do tensorflow: **tf.keras**.

# 🎲 Tensors e Operações

Geralmente, um *tensor* é um array multidimensional, exatamente com oum *ndarray* da **NumPy**, mas ele também pode conter um escalar (um valor simples, como 42). Esses tensores sãoimportantes para criar funções de custos e métricas customizadas, camadas personalizadas etc.

In [1]:
import tensorflow as tf

In [2]:
tf.constant([[1., 2., 3.], [4., 5., 6.]]) #Matriz

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [3]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

podemos ver o shape e o dtype dessas constants

In [4]:
array_tf = tf.constant([[1., 2., 3.], [4., 5., 6.]]) #Matriz
array_tf.shape

TensorShape([2, 3])

In [5]:
array_tf.dtype

tf.float32

indexação funciona como no numpy

In [6]:
array_tf[:, 1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [7]:
array_tf[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

tipo de operações

In [8]:
tf.square(array_tf)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [9]:
array_tf + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [10]:
array_tf @ tf.transpose(array_tf) # O @ é uma multiplicação de matrizes, note que ela multiplicou seus valores, nesse caso, está trocando as linhas pelas colunas com o transpose

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

essas não são as únicas operações possíveis, o TensorFlow basicamente faz tudo o que o numpy faz, algumas funções podem ter nomes diferentes, mas se procurar, achará.

# 📗 Tensores e numpy

É possível criar um tensor a partir de um array *NumPy* e vice-versa:

In [11]:
import numpy as np

In [14]:
a = np.array([2., 4., 5.])
a

array([2., 4., 5.])

In [15]:
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [16]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [17]:
np.square(array_tf)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

O TensorFlow não faz nenhuma conversão de tipos, caso tente realizar alguma opreção com tipos diferentes de variáveis, obterá um erro:

In [18]:
tf.constant(2.) + tf.constant(40)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 

o erro abaixo é pelo fato do tensorflow utilizar float32 ao invés de float64, essa diferença ajuda na performance.

In [22]:
tf.constant(2.) + tf.constant(40., dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2] name: 

se precisar converter um tipo, utilize o **tf.cast**

In [24]:
t2 = tf.constant(40., dtype=tf.float64)

In [25]:
tf.constant(2.0) + tf.cast(t2, tf.float32) # convertendo primeiro para float32

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

# 🎲 Variáveis

Os valores de tf.Tensor são imutáveis, não podemos utilizar tensors regulares para implementar pesos em uma rede neural, pois eles precisam ser ajustados pela retropropagação. Além disso, outros parâmtros também precisam mudar ao longo do tempo, para isso, utilizamos variáveis tensors:

Essa parte dificilmente é usada, pois para adicionarmos pesos temos o **add_weight()**, além de que parâmetros já são atualizados pelos otimizadores.

In [27]:
a = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
a

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [28]:
a.assign(2 * a)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [29]:
a[:, 2].assign([0., 1.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  0.],
       [ 8., 10.,  1.]], dtype=float32)>

In [31]:
a.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[100., 200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,   4.,   0.],
       [  8.,  10., 200.]], dtype=float32)>